name: $(date:yyyyMMdd)$(rev:.rr) #20200319.00

pr:
  - master
  
stages:
  - stage: build
    jobs:
      - job:
        vmImage: ubuntu-18.04
        steps:
            - script: dotnet build

  - stage: test
    jobs:
      - job: test
        pool:
          vmImage: ubuntu-18.04
        steps:
          - script: dotnet test --collect:"XPlat Code Coverage"
  
  - stage: pack
    jobs:
      - job:
        pool:
          vmImage: ubuntu-18.04
        steps: |
          - script:
            docker login
            docker image build -f dockerfile -t jesusguerecab/p1proj .
            docker image push jesusguerecab/p1proj
            docker logout

trigger:
  - master
